from setuptools import setup

setup(
    name='ith',
    version='1.0.0',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    install_requires=[
        '',
        '',
        '',
        'Keras == 2.4.3',
        '',
        '',
        '',
        'Pillow == 6.2.0',
        '',
        '',
        'gensim == 3.8.3',
        '',
        '',
        'imageio == 2.6.0',
        '',
        '',
        'ipython == 7.8.0',
        '',
        '',
        'matplotlib == 3.1.3',
        '',
        '',
        'nltk == 3.4.5',
        '',
        '',
        '',
        '',
        'numpy == 1.17.2',
        '',
        '',
        'opencv_python == 4.5.1.48',
        '',
        '',
        '',
        '',
        'pandas == 0.25.1',
        '',
        '',
        'requests == 2.22.0',
        '',
        '',
        'scikit_image == 0.15.0',
        '',
        '',
        'setuptools == 41.4.0',
        '',
        '',
        '',
        'torch == 1.8.1',
        '',
        '',
        '',
        'torchvision == 0.9.1',
    ],
)
